config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'logout', to: 'sessions#destroy'

  get 'steps', to: 'portfolios#step'

  get 'pass', to: 'stocks_users#pass'

  get '/portfolios/:id/getting_started', to: 'portfolios#getting_started', as: 'getting_started'

  resources :users, only: ["new", "create"]

  resources :portfolios

  resources :stocks_users, only: ["create"]

  resources :stocks, only: ["show"]

  resources :industries, only: ["index", "show"]

  resources :sessions, only: ["create", "destroy"]

  get 'test', to: 'page#test'

  get "portfolios/:id/fetch", :to => "portfolios#fetch"
  
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

  belongs_to :user
  has_many :holdings
  has_many :stocks, through: :holdings
  accepts_nested_attributes_for :holdings,
    :allow_destroy => true,
    :reject_if     => :all_blank
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  helper_method :hash_to_array

  # Sample code to use Quandl gem to made api request
  # =====================================================================================
  # @snp = Quandl::Dataset.get("YAHOO/INDEX_GSPC").data(params: { start_date: "2016-01-01", end_date: "2016-04-22" }) # ["date", "open", "high", "low", "close", "volume", "adjusted_close"]
  # @snp_result = yahoo_table(@snp)

  # @nasdaq = Quandl::Dataset.get("NASDAQOMX/COMP").data(params: {start_date: "2016-01-01", end_date: "2016-04-08" }) # ["trade_date", "index_value", "high", "low", "total_market_value", "dividend_market_value"]
  # @nasdaq_result = nasdaq_table(@nasdaq)

  # @dji = Quandl::Dataset.get("YAHOO/INDEX_DJI").data(params: {start_date: "2016-01-01", end_date: "2016-04-22" }) # ["date", "open", "high", "low", "close", "volume", "adjusted_close"]
  # @dji_result = yahoo_table(@dji)

  # @company = "AAPL"
  # @stock = Quandl::Dataset.get("WIKI/#{@company}").data(params: { start_date: "2016-01-01", end_date: "2016-04-22" }) # ["date", "open", "high", "low", "close", "volume", "ex_dividend", "split_ratio", "adj_open", "adj_high", "adj_low", "adj_close", "adj_volume"]
  # @stock_result = stock_table(@stock)

  # GET /portfolios
  # GET /portfolios.json
  def step
    render "steps"
  end

  def index
    if user_signed_in?
      @user = User.find(session[:id])
      @portfolios = @user.portfolios
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    # @count = User.find(session[:id]).portfolios.count
    @portfolio = Portfolio.find(params[:id])
    @holdings = @portfolio.holdings

  end

  def fetch

    if request.xhr?
      @portfolio = Portfolio.find(params[:id])
      @holdings = @portfolio.holdings
      @portfolio_data = zippy(@holdings,@portfolio.start_time, @portfolio.end_time)
      @nasdaq= index_data("nasdaq",@portfolio.start_time, @portfolio.end_time)
      @snp= index_data("snp",@portfolio.start_time, @portfolio.end_time)
      @dji= index_data("dji",@portfolio.start_time, @portfolio.end_time)
      @news = []
      @holdings.each do |holding|
        name =Stock.find_by(symbol: holding.symbol).name
        @news << [holding.symbol, nytimes(name, @portfolio.start_time.tr('-',''), @portfolio.end_time.tr('-','') )]
      end
      render :json => {"stocks" => @portfolio_data, "snp" => @snp, "nasdaq" => @nasdaq, "dji" => @dji, "title" => @portfolio.name, "articles" => @news, "holdings" => @holdings }
    end
  end

  def getting_started
  end

  # GET /portfolios/new
  def new
    session[:index] = nil
    session[:stock] = nil
    @user = User.find(session[:id])
    @portfolio = Portfolio.new
    @selections = @user.stocks
    num_of_stocks = StocksUser.where(user_id: session[:id]).count
    num_of_stocks.times{@portfolio.holdings.build}
    @holdings = @portfolio.holdings
  end

  # GET /portfolios/1/edit
  def edit
    @user = User.find(session[:id])
    @portfolio = Portfolio.find(params[:id])
    @selections = @portfolio.holdings
    @holdings = @portfolio.holdings
  end

  # POST /portfolios
  # POST /portfolios.json
  def create

    @portfolio = Portfolio.create(portfolio_params)
    @user = User.find(session[:id])
    @user.portfolios << @portfolio
    StocksUser.where(user_id: session[:id]).destroy_all
    redirect_to portfolios_path


    # respond_to do |format|
    #   if @portfolio.save
    #     format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
    #     format.json { render :show, status: :created, location: @portfolio }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @portfolio.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])
    @user = User.find(session[:id])
    StocksUser.where(user_id: session[:id]).destroy_all
    @portfolio.update(portfolio_params)

    redirect_to portfolios_path
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:name,:description, :user_id,:start_time,:end_time, :image_url, holdings_attributes: [:id,:symbol, :allocation, :_destroy])
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def api
    result = RestClient.get "http://api.nytimes.com/svc/search/v2/articlesearch.json?callback=svc_search_v2_articlesearch&q=finance&begin_date=20140101&end_date=20150101&sort=oldest&api-key=#{ENV['NYTIME_KEY']}"
    parsed = JSON.parse(result)
  end

end

app/views/portfolios/_form.html.erb
<%= form_for @portfolio do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-style-8">
  <h2>Please Fill Out The Form Below</h2>
  <form>
    <div class="field">
      Name<br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      Description<br>
      <%= f.text_field :description, value: "#{@portfolio.try(:description)}" %>
    </div>
    <div class="field">
      Start-time<br>
      <%= f.date_field :start_time, value: "#{@portfolio.try(:start_time)}" %>
    </div>
    <div class="field">
      End-time<br>
      <%= f.date_field :end_time, value: "#{@portfolio.try(:end_time)}"  %>
    </div>

    <% i = 0 %>
      <%= f.fields_for :holdings do |ff| %>
      <div class="form-divider">
        <div class="field">
          Symbol<br>
          <%= ff.text_field :symbol, :value => @selections[i].try(:symbol) %>
        </div>
        <div class="field">
          Allocation<br>
          <%= ff.number_field :allocation, :value => @selections[i].try(:allocation) %>
        </div>
        <% if ff.object.persisted? %>
        <div class="field">
          <div class="delete-checkbox">Delete</div>
          <div class="delete-checkbox"><%= ff.check_box :_destroy, style: "height:50px;" %></div>
        </div>
        <% end %>
      </div>

      <% i += 1 %>
    <% end %>
  </form>
  <div class="container-fluid">
    <%#= button_to 'Back', portfolios_path, :method => "get", :class => "btn btn-primary btn-sm" %>
    <%= button_tag "Cancel", :class => "btn btn-primary btn-sm", :onclick => "location.href = '#{portfolios_path}'" %>
    <%= f.submit :class => "btn btn-primary btn-sm" %>
  </div>
<% end %>


<script type="text/javascript">
//auto expand textarea
function adjust_textarea(h) {
    h.style.height = "20px";
    h.style.height = (h.scrollHeight)+"px";
}
</script>

app/views/portfolios/edit.html.erb
<div class="container">

  <h1>Editing Portfolio</h1>

  <%= render 'form', layout: false %>

</div>

app/views/portfolios/index.html.erb
<%# if api.any? %>

<%# else %>

<section class="container portfolio">
  <p id="notice"><%= notice %></p>
  <% i = 1 %>
  <% @portfolios.each do |portfolio| %>

  <div class="wrapper">
    <div class="card radius shadowDepth1">
      <div class="card__image border-tlr-radius">
        <img src="http://lorempixel.com/400/200/sports/" alt="image" class="border-tlr-radius">
      </div>

      <div class="card__content card__padding">
        <div class="card__share">
          <div class="card__social">
            <%= link_to 'Edit', edit_portfolio_path(portfolio.id), class: "share-icon facebook" %></a>
            <%= link_to 'Destroy', portfolio, class: "share-icon googleplus", method: :delete, data: { confirm: 'Are you sure?' } %></a>
          </div>
          <a id="share" class="share-toggle share-icon" href="#"></a>
        </div>

        <div class="card__meta">
          <time><%= portfolio.created_at.strftime("%b %d %Y") %></time>
        </div>

        <article class="card__article">
          <h4><%= link_to portfolio.name, portfolio_path(portfolio.id) %></h4>
          <!-- Description for each portfolio goes here -->
          <p style="font-size: 13px"><%= portfolio.description %></p>
        </article>
      </div>


    </div>
  </div>
  <% i += 1 %>
  <% end %>
  <%= link_to 'New Portfolio', industries_path, class: "btn btn-primary container-fluid" %>
</section>


<!-- <div class="container"> -->
<%#=@news%>
<%#=@news["response"]%>
<!-- </div> -->

<!-- High Chart JavaScript -->
<!-- <script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>

<script src="assets/portfolio.js"></script> -->
<script src="assets/dashboard.js"></script>

app/views/portfolios/new.html.erb
<div class="container">
  <h1>New Portfolio</h1>

  <%= render 'form', layout: false %>

</div>

app/views/portfolios/show.html.erb
    <!-- Bootstrap Core CSS -->
    <link href="/assets/dashboard/bootstrap.min.scss" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/dashboard/sb-admin.scss" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/assets/font-awesome.scss" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

<p><span class="hidden_portfolio_id"><%= @portfolio.id %></span></p>
    <div id="wrapper">

        <div id="page-wrapper">
            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
<!--                         <h1 class="page-header">
                            Dashboard <small>Statistics Overview</small>
                        </h1> -->
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                <div class="header-container">
                  <div class="col-lg-3 col-md-6 tabs">
                      <div class="panel panel-green">
                          <div class="panel-heading">
                              <div class="row">
                                  <div class="col-xs-3">
                                      <i class="fa fa-clipboard fa-5x"></i>
                                  </div>
                                  <div class="col-xs-9 text-right">
                                      <div class="huge"><%=  @holdings.count %></div>
                                      <div>Stocks!</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6 tabs">
                      <div class="panel panel-yellow">
                          <div class="panel-heading">
                              <div class="row">
                                  <div class="col-xs-3">
                                      <i class="fa fa-calendar-o fa-5x"></i>
                                  </div>
                                  <div class="col-xs-9 text-right">
                                  <% start_date = DateTime.parse(@portfolio.start_time).to_date %>
                                      <div class="huge"><%= start_date.strftime('%d %b %Y') %></div>
                                      <div>Start Date!</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6 tabs">
                      <div class="panel panel-red">
                          <div class="panel-heading">
                              <div class="row">
                                  <div class="col-xs-3">
                                      <i class="fa fa-calendar fa-5x"></i>
                                  </div>
                                  <div class="col-xs-9 text-right">
                                  <% end_date = DateTime.parse(@portfolio.end_time).to_date %>
                                      <div class="huge"><%= end_date.strftime('%d %b %Y') %></div>
                                      <div>End Date!</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </div>

                    <div class="col-lg-4 pie">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-long-arrow-right fa-fw"></i> Pie Chart</h3>
                      </div>
                      <div id="pie-chart">
                        <div class="panel-body">
                          <div class="sk-folding-cube">
                            <div class="sk-cube1 sk-cube"></div>
                            <div class="sk-cube2 sk-cube"></div>
                            <div class="sk-cube4 sk-cube"></div>
                            <div class="sk-cube3 sk-cube"></div>
                          </div>
                        </div>
                      </div>
                      </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Stock Chart</h3>
                            </div>
                            <div class="panel-body">
                                <div id="chart"></div>
                                <div class="panel-body">
                                <div class="sk-folding-cube">
                                  <div class="sk-cube1 sk-cube"></div>
                                  <div class="sk-cube2 sk-cube"></div>
                                  <div class="sk-cube4 sk-cube"></div>
                                  <div class="sk-cube3 sk-cube"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
                <!-- News Section (Stretch Goal) -->
                    <!-- <div class="col-lg-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> Recent News</h3>
                            </div>

                            <div class="panel-body">
                                <div class="list-group">
                                    <a href="#" class="list-group-item">
                                        <span class="badge">just now</span>
                                        <i class="fa fa-fw fa-calendar"></i> Yahoo got bankrupt today!
                                    </a>
                            </div>
                        </div>
                      </div> -->
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="/assets/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/bootstrap.min.js"></script>

<!-- High Chart JavaScript -->
<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>

<script src="/assets/highcharts.js"></script>

app/views/portfolios/steps.html.erb
<!-- JS -->
    <!-- load angular, nganimate, and ui-router -->
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.10/angular-ui-router.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular-animate.min.js"></script>
    <script src="assets/portfolio.js"></script>

<div ng-app="yourApp">
<div ng-controller="stepCtrl">
<div ng-switch="step">
<div ng-switch-when="1">
<!-- here you can include your step 1 template,
or simply just hardcode it here: -->
<div ng-include src="'http://www.google.com'">
<button ng-click="setStep(1)"></button>
</div>
<div ng-switch-when="2">
<div ng-include src="'.../step2.html'">
<button ng-click="setStep(2)"></button>
</div>
<div ng-switch-when="3">
<div ng-include src="'.../step3.html'">
<button ng-click="setStep(3)"></button>
</div>
</div>
</div>
  </div>

<script type="text/javascript">
yourApp.controller('stepCtrl',function($scope){
$scope.step = 1;
$scope.setStep = function(step){
$scope.step = step;
}
});
app.config(function($stateProvider, $urlRouterProvider) {
$stateProvider
.state('wizard', {// this will be the wrapper for our wizard
url: '/wizard',
templateUrl: 'wizard.html',
controller: 'wizardController'
})
.state('wizard.stepOne', {// this will be the wrapper for our wizard
url: '/stepOne',
templateUrl: 'stepOne.html',
controller: 'wizardController'
})
.state('wizard.stepTwo', {// this will be the wrapper for our wizard
url: '/stepTwo',
templateUrl: 'stepTwo.html',
controller: 'wizardController'
});

<div id="container">
<div>
<h2>Our multistep form wizard</h2>
<div id="status-buttons" class="text-center">
<a ui-sref-active="active" ui-sref=".stepOne"><span>1</span> Step One</a>
<a ui-sref-active="active" ui-sref=".stepTwo"><span>2</span> Step Two </a>
</div>
</div>
<!-- Here we specify our view that is a container for our subviews(steps) , which in our case can be a form !-->
<form id="signup-form" ng-submit="submit()">

<div ui-view></div>
</form>
</div>

</script>