config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'logout', to: 'sessions#destroy'

  get 'steps', to: 'portfolios#step'

  get 'pass', to: 'stocks_users#pass'

  get '/portfolios/:id/getting_started', to: 'portfolios#getting_started', as: 'getting_started'

  resources :users, only: ["new", "create"]

  resources :portfolios

  resources :stocks_users, only: ["create"]

  resources :stocks, only: ["show"]

  resources :industries, only: ["index", "show"]

  resources :sessions, only: ["create", "destroy"]

  get 'test', to: 'page#test'

  get "portfolios/:id/fetch", :to => "portfolios#fetch"
  
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :holdings
  has_many :stocks_users
  has_many :users, through: :stocks_users
  has_many :portfolios, through: :holdings

  belongs_to :industry
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stocks = Stock.all
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:symbol, :name, :description, :request_token, :request_key)
    end
end

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :request_token %><br>
    <%= f.text_field :request_token %>
  </div>
  <div class="field">
    <%= f.label :request_key %><br>
    <%= f.text_field :request_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Name</th>
      <th>Description</th>
      <th>Request token</th>
      <th>Request key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.symbol %></td>
        <td><%= stock.name %></td>
        <td><%= stock.description %></td>
        <td><%= stock.request_token %></td>
        <td><%= stock.request_key %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @stock.symbol %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @stock.description %>
</p>

<p>
  <strong>Description:</strong>
  <%= @stock.description %>
</p>

<p>
  <strong>Request token:</strong>
  <%= @stock.request_token %>
</p>

<p>
  <strong>Request key:</strong>
  <%= @stock.request_key %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>