config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'logout', to: 'sessions#destroy'

  get 'steps', to: 'portfolios#step'

  get 'pass', to: 'stocks_users#pass'

  get '/portfolios/:id/getting_started', to: 'portfolios#getting_started', as: 'getting_started'

  resources :users, only: ["new", "create"]

  resources :portfolios

  resources :stocks_users, only: ["create"]

  resources :stocks, only: ["show"]

  resources :industries, only: ["index", "show"]

  resources :sessions, only: ["create", "destroy"]

  get 'test', to: 'page#test'

  get "portfolios/:id/fetch", :to => "portfolios#fetch"
  
end

app/models/stock_user.rb
class StockUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
end

app/controllers/stock_users_controller.rb
class StockUsersController < ApplicationController
  before_action :set_stock_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /stock_users
  # GET /stock_users.json
  def index
    @stock_users = StockUser.all
  end

  # GET /stock_users/1
  # GET /stock_users/1.json
  def show
    redirect_to industry_path(session[:industry_id])
  end

  # GET /stock_users/new
  def new
    @stock_user = StockUser.new
  end

  # GET /stock_users/1/edit
  def edit
  end

  # POST /stock_users
  # POST /stock_users.json
  def create
    if request.xhr?
       @stock_user = StockUser.new(stock_user_params)
       if @stock_user.save
         render json: "200"
       else
          render json: "500"
       end
    else
      @stock_user = StockUser.new(stock_user_params)
      redirect_to @stock_user
    end


    # respond_to do |format|
    #   if @stock_user.save
    #     format.html { redirect_to @stock_user, notice: 'Stock user was successfully created.' }
    #     format.json { render :show, status: :created, location: @stock_user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @stock_user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /stock_users/1
  # PATCH/PUT /stock_users/1.json
  def update
    respond_to do |format|
      if @stock_user.update(stock_user_params)
        format.html { redirect_to @stock_user, notice: 'Stock user was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_user }
      else
        format.html { render :edit }
        format.json { render json: @stock_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_users/1
  # DELETE /stock_users/1.json
  def destroy
    @stock_user.destroy
    respond_to do |format|
      format.html { redirect_to stock_users_url, notice: 'Stock user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_user
      @stock_user = StockUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_user_params
      params.require(:stock_user).permit(:user_id, :stock_id)
    end
end

app/views/stock_users/_form.html.erb
<%= form_for(@stock_user) do |f| %>
  <% if @stock_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock_user.errors.count, "error") %> prohibited this stock_user from being saved:</h2>

      <ul>
      <% @stock_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :stock_id %><br>
    <%= f.text_field :stock_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stock_users/new.html.erb
<h1>New Stock User</h1>

<%= render 'form' %>

<%= link_to 'Back', stock_users_path %>

app/views/stock_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @stock_user.user %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @stock_user.stock %>
</p>

<%= link_to 'Edit', edit_stock_user_path(@stock_user) %> |
<%= link_to 'Back', stock_users_path %>