config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'logout', to: 'sessions#destroy'

  get 'steps', to: 'portfolios#step'

  get 'pass', to: 'stocks_users#pass'

  get '/portfolios/:id/getting_started', to: 'portfolios#getting_started', as: 'getting_started'

  resources :users, only: ["new", "create"]

  resources :portfolios

  resources :stocks_users, only: ["create"]

  resources :stocks, only: ["show"]

  resources :industries, only: ["index", "show"]

  resources :sessions, only: ["create", "destroy"]

  get 'test', to: 'page#test'

  get "portfolios/:id/fetch", :to => "portfolios#fetch"
  
end

app/models/stocks_user.rb
class StocksUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
end

app/controllers/stocks_users_controller.rb
class StocksUsersController < ApplicationController
  before_action :set_stock_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /stock_users
  # GET /stock_users.json
  def index
    @stocks_users = StocksUser.all
  end

  # GET /stock_users/1
  # GET /stock_users/1.json
  def show
    redirect_to industry_path(session[:industry_id])
  end

  # GET /stock_users/new
  def new
    @stocks_user = StocksUser.new
  end

  # GET /stock_users/1/edit
  def edit
  end

  # POST /stock_users
  # POST /stock_users.json
  def create

    if session[:index].nil?
      session[:index] = 0
    else
      session[:index] += 1
    end

    if request.xhr?

      @stock_id = Stock.find_by(symbol: params["symbol"]).id
      @user_id = session[:id]
      @stocks_user = StocksUser.new(user_id: @user_id, stock_id: @stock_id)
      session[:stocks].pop

      if @stocks_user.save
        render json: "200"
      else
        render json: "500"
      end
    else
      #redirect_to previous page
    end

  end

    def pass
      if request.xhr?
        p "*"*100
        session[:stocks].pop
        render json: "200"
      end
    end

  # PATCH/PUT /stock_users/1
  # PATCH/PUT /stock_users/1.json
  def update
    respond_to do |format|
      if @stocks_user.update(stock_user_params)
        format.html { redirect_to @stocks_user, notice: 'Stock user was successfully updated.' }
        format.json { render :show, status: :ok, location: @stocks_user }
      else
        format.html { render :edit }
        format.json { render json: @stocks_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_users/1
  # DELETE /stock_users/1.json
  def destroy
    @stock_user.destroy
    respond_to do |format|
      format.html { redirect_to stock_users_url, notice: 'Stock user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_user
      @stocks_user = StocksUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stocks_user_params
      params.require(:stock_user).permit(:user_id, :stock_id)
    end
end

app/views/stocks_users/_form.html.erb
<%= form_for(@stocks_user) do |f| %>
  <% if @stocks_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stocks_user.errors.count, "error") %> prohibited this stock_user from being saved:</h2>

      <ul>
      <% @stocks_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :stock_id %><br>
    <%= f.text_field :stock_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks_users/edit.html.erb
<h1>Editing Stock User</h1>

<%= render 'form' %>

<%= link_to 'Show', @stocks_user %> |
<%= link_to 'Back', stocks_users_path %>

app/views/stocks_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stock Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks_users.each do |stocks_user| %>
      <tr>
        <td><%= stocks_user.user %></td>
        <td><%= stocks_user.stock %></td>
        <td><%= link_to 'Show', stocks_user %></td>
        <td><%= link_to 'Edit', edit_stocks_user_path(stock_user) %></td>
        <td><%= link_to 'Destroy', stocks_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock user', new_stocks_user_path %>

app/views/stocks_users/new.html.erb
<h1>New Stock User</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_users_path %>

app/views/stocks_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @stock_user.user %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @stock_user.stock %>
</p>

<%= link_to 'Edit', edit_stocks_user_path(@stocks_user) %> |
<%= link_to 'Back', stocks_users_path %>